### ISSUE TITLE
Best not to leave your API keys on github :P

### ISSUE THREAD

**Issue by connorslade** [0n3Appl3/solaris#1]
In your Chatbot feature, one line says 
```fetch(`https://api.monkedev.com/fun/chat?msg=${message.content.replace(bot_info.mention, '')}&uid=${message.author.id}&key=[key hidden]`)```

This has your API key in it and if that key were spamed it could cause a rate limit which would crash the bot...

**Comment by 0n3Appl3** [comment]
Thanks for letting me know earlier today! Resolved.
